# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.80"

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
  config.vm.provision "file", source: "./docker-compose.yaml", destination: "/home/vagrant/docker-compose.yaml"
  config.vm.provision "file", source: "./app.py", destination: "/home/vagrant/app.py"
  config.vm.provision "file", source: "./dockerfile", destination: "/home/vagrant/dockerfile"
  config.vm.provision "file", source: "./nginx.conf", destination: "/home/vagrant/nginx.conf"

  #To install, rebuild and run docker-compose on vagrant up
  config.vm.provision :docker 
  config.vm.provision :docker_compose

  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    apt-get update
    apt-get install -y nginx
    docker build -t app1 -f /home/vagrant/dockerfile /home/vagrant
    cd /home/vagrant/ && docker-compose up -d
    rm /etc/nginx/nginx.conf
    cp /home/vagrant/nginx.conf /etc/nginx
    nginx -s reload
  SHELL
end