# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "private_network", ip: "192.168.33.76"

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
  config.vm.provision "file", source: "./setup_nginx.sh", destination: "/home/vagrant/setup_nginx.sh"
  config.vm.provision "file", source: "./nginx.conf", destination: "/home/vagrant/nginx.conf"
  config.vm.provision "file", source: "../simple_app.tar", destination: "/home/vagrant/simple_app.tar"


  
  config.vm.provision "shell", inline: <<-SHELL
  cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  ./setup_nginx.sh
  SHELL

end
